<h1>Customer List</h1>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>id</td>
            <td>name</td>
            <td>email</td>
            <td>phone</td>
        </tr>
    </tbody>
</table>