<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ConsultSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table("consults")->insert([
            [
                "consult_id" => "aaaaaaaaaaaaa",
                "user_id" => "3333333333333",
                "status" => "draft",
                "patient_firstname" => "Chutikan",
                "patient_lastname" => "Meeluck",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "diabetes",
                "med_dx" => "diabetes",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "",
                "created_at" => Carbon::create(2015, 1, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "bbbbbbbbbbbbb",
                "user_id" => "3333333333333",
                "status" => "pending",
                "patient_firstname" => "Chutikan",
                "patient_lastname" => "Meeluck",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "diabetes",
                "med_dx" => "diabetes",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "",
                "created_at" => Carbon::create(2015, 2, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "ccccccccccccc",
                "user_id" => "3333333333333",
                "status" => "done",
//                "patient_firstname" => "Chutikan",
//                "patient_lastname" => "Meeluck",
                "patient_firstname" => "Adele",
                "patient_lastname" => "Magana",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "diabetes",
                "med_dx" => "diabetes",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2015, 3, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "ddddddddddddd",
                "user_id" => "3333333333333",
                "status" => "done",
                "patient_firstname" => "Conall",
                "patient_lastname" => "Magana",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "diabetes",
                "med_dx" => "diabetes",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2015, 4, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "eeeeeeeeeeeee",
                "user_id" => "3333333333333",
                "status" => "done",
                "patient_firstname" => "Maximus",
                "patient_lastname" => "Rojas",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "diabetes",
                "med_dx" => "diabetes",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2015, 5, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "fffffffffffff",
                "user_id" => "3333333333333",
                "status" => "done",
                "patient_firstname" => "Miya",
                "patient_lastname" => "Booth",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "alzheimer's disease",
                "med_dx" => "alzheimer's disease",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2015, 6, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "ggggggggggggg",
                "user_id" => "3333333333333",
                "status" => "done",
                "patient_firstname" => "Raife",
                "patient_lastname" => "Adamson",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "bipolar disorder",
                "med_dx" => "bipolar disorder",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2015, 7, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "hhhhhhhhhhhhh",
                "user_id" => "3333333333333",
                "status" => "done",
                "patient_firstname" => "Leonard",
                "patient_lastname" => "Manning",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "chronic kidney disease",
                "med_dx" => "chronic kidney disease",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2015, 8, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "iiiiiiiiiiiii",
                "user_id" => "8888888888888",
                "status" => "done",
                "patient_firstname" => "Manning",
                "patient_lastname" => "Leonard",
                "patient_dob" => "1986-04-15",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "headache",
                "med_dx" => "Hypertension",
                "med_bw" => "55",
                "med_bmi" => "21",
                "med_t" => "37",
                "med_fbs" => "120",
                "med_cr" => "0.3",
                "med_clearance" => "117",
                "med_stage" => "1",
                "rec01_date" => "2015-5-10",
                "rec01_fbs" => "120",
                "rec01_bp1" => "141/90",
                "rec01_bp2" => "140/89",
                "rec01_p" => "89",
                "rec02_date" => "2015-6-10",
                "rec02_fbs" => "120",
                "rec02_bp1" => "141/89",
                "rec02_bp2" => "140/89",
                "rec02_p" => "89",
                "consult_complain" => "pt. need to extract teeth",
                "consult_plan" => "amlodipine",
                "consult_order" => "pt. could do routine treatment with good care about bleeding",
                "created_at" => Carbon::create(2016, 1, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "jjjjjjjjjjjjj",
                "user_id" => "3333333333333",
                "status" => "done",
                "patient_firstname" => "Aleksander",
                "patient_lastname" => "Elena",
                "patient_dob" => "1986-04-15",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "obese",
                "med_dx" => "DM",
                "med_bw" => "107",
                "med_bmi" => "32",
                "med_t" => "36.6",
                "med_fbs" => "136",
                "med_cr" => "1.1",
                "med_clearance" => "115",
                "med_stage" => "1",
                "rec01_date" => "2015-5-10",
                "rec01_fbs" => "136",
                "rec01_bp1" => "128/60",
                "rec01_bp2" => "130/59",
                "rec01_p" => "75",
                "rec02_date" => "",
                "rec02_fbs" => "",
                "rec02_bp1" => "",
                "rec02_bp2" => "",
                "rec02_p" => "",
                "consult_complain" => "sleep apnea",
                "consult_plan" => "metromin, symvastatin",
                "consult_order" => "do a sleep lab",
                "created_at" => Carbon::create(2016, 2, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],

//            --------------------------------------------------------------------------------------------------------------------

            [
                "consult_id" => "kkkkkkkkkkkkk",
                "user_id" => "8888888888888",
                "status" => "done",
                "patient_firstname" => "Annabell",
                "patient_lastname" => "Mcdowell",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "chronic kidney disease",
                "med_dx" => "chronic kidney disease",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2016, 3, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "lllllllllllll",
                "user_id" => "8888888888888",
                "status" => "done",
                "patient_firstname" => "Aleksander",
                "patient_lastname" => "Lowery",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "chronic kidney disease",
                "med_dx" => "chronic kidney disease",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "consult order test",
                "created_at" => Carbon::create(2016, 4, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "mmmmmmmmmmmmm",
                "user_id" => "3333333333333",
                "status" => "draft",
                "patient_firstname" => "Lorelei",
                "patient_lastname" => "Vazquez",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "alzheimer's disease",
                "med_dx" => "alzheimer's disease",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "",
                "created_at" => Carbon::create(2016, 5, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "nnnnnnnnnnnnn",
                "user_id" => "3333333333333",
                "status" => "draft",
                "patient_firstname" => "Elena",
                "patient_lastname" => "Townsend",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "bipolar disorder",
                "med_dx" => "bipolar disorder",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "",
                "created_at" => Carbon::create(2016, 6, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "ooooooooooooo",
                "user_id" => "3333333333333",
                "status" => "pending",
                "patient_firstname" => "Bree",
                "patient_lastname" => "Townsend",
                "patient_dob" => "1986-04-14",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "chronic kidney disease",
                "med_dx" => "chronic kidney disease",
                "med_bw" => "65",
                "med_bmi" => "26.6",
                "med_t" => "37",
                "med_fbs" => "100",
                "med_cr" => "0.43",
                "med_clearance" => "122.1",
                "med_stage" => "1",
                "rec01_date" => "2014-5-10",
                "rec01_fbs" => "100",
                "rec01_bp1" => "200/90",
                "rec01_bp2" => "110/90",
                "rec01_p" => "120",
                "rec02_date" => "2014-6-10",
                "rec02_fbs" => "130/76",
                "rec02_bp1" => "110/80",
                "rec02_bp2" => "120/80",
                "rec02_p" => "70",
                "consult_complain" => "FBS >= 130 mg%",
                "consult_plan" => "Slmvas 1209 1/2 x ns",
                "consult_order" => "",
                "created_at" => Carbon::create(2016, 7, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "ppppppppppppp",
                "user_id" => "8888888888888",
                "status" => "pending",
                "patient_firstname" => "Robin",
                "patient_lastname" => "Zamora",
                "patient_dob" => "1986-04-15",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "headache",
                "med_dx" => "Hypertension",
                "med_bw" => "55",
                "med_bmi" => "21",
                "med_t" => "37",
                "med_fbs" => "120",
                "med_cr" => "0.3",
                "med_clearance" => "117",
                "med_stage" => "1",
                "rec01_date" => "2015-5-10",
                "rec01_fbs" => "120",
                "rec01_bp1" => "141/90",
                "rec01_bp2" => "140/89",
                "rec01_p" => "89",
                "rec02_date" => "2015-6-10",
                "rec02_fbs" => "120",
                "rec02_bp1" => "141/89",
                "rec02_bp2" => "140/89",
                "rec02_p" => "89",
                "consult_complain" => "pt. need to extract teeth",
                "consult_plan" => "amlodipine",
                "consult_order" => "",
                "created_at" => Carbon::create(2016, 8, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
            [
                "consult_id" => "qqqqqqqqqqqqq",
                "user_id" => "8888888888888",
                "status" => "pending",
                "patient_firstname" => "Potter",
                "patient_lastname" => "Wise",
                "patient_dob" => "1986-04-15",
                "patient_gender" => "Male",
                "patient_address" => "239 Huaykaew Rd., Suthep, Muang, Chiang Mai",
                "primary_doctor" => "Dr. James Gordon",
                "health_condition" => "obese",
                "med_dx" => "DM",
                "med_bw" => "107",
                "med_bmi" => "32",
                "med_t" => "36.6",
                "med_fbs" => "136",
                "med_cr" => "1.1",
                "med_clearance" => "115",
                "med_stage" => "1",
                "rec01_date" => "2015-5-10",
                "rec01_fbs" => "136",
                "rec01_bp1" => "128/60",
                "rec01_bp2" => "130/59",
                "rec01_p" => "75",
                "rec02_date" => "",
                "rec02_fbs" => "",
                "rec02_bp1" => "",
                "rec02_bp2" => "",
                "rec02_p" => "",
                "consult_complain" => "sleep apnea",
                "consult_plan" => "metromin, symvastatin",
                "consult_order" => "",
                "created_at" => Carbon::create(2016, 9, 1, 0, 0, 0)->format('Y-m-d H:i:s')
            ],
        ]);
    }
}
